#!/usr/bin/env node
'use strict';
// Derives prototype_capture.html (beside this file) FROM ../inkwood-renderer.html
// by string replacement -- never a hand copy, so the capture page draws exactly
// what the prototype draws. Each replacement must match exactly once or the
// script fails; when the prototype changes, re-run it:
//
//     node reference/port_check/make_capture_page.js
//
// What it changes, and nothing else:
//   1. DPR is forced to 1 (the prototype uses min(2, devicePixelRatio)), so the
//      map canvas is exactly as many pixels as CSS says, as in Godot (DPR 1).
//   2. The stage is fixed at exactly 1280x720 CSS px (the prototype sizes it to
//      the window), so W, H -- and with them the road, the fort and every tree
//      the scene generator places for seed 20261009 -- match the Godot frame.
//   3. render() counts its frames in window.__inkFrames (one statement prepended
//      to its last line), so the page can tell when the first scene is drawn.
//   4. A script appended at the end: after the first render it exposes
//      window.captureMap() -> the map canvas as a PNG data URL, resolves
//      window.captureReady, and shows a "Save PNG" button that downloads it.
//
// The grain is Math.random() in the prototype and differs on every load; untick
// "Grain" under Render passes for a capture that can be compared pixel for pixel.

const fs = require('fs');
const path = require('path');

const here = __dirname;
const srcPath = path.join(here, '..', 'inkwood-renderer.html');
const outPath = path.join(here, 'prototype_capture.html');
let html = fs.readFileSync(srcPath, 'utf8');

function replaceOnce(find, replacement, why) {
  const first = html.indexOf(find);
  if (first < 0) throw new Error(`prototype changed? not found (${why}): ${find}`);
  if (html.indexOf(find, first + find.length) >= 0) throw new Error(`matched more than once (${why}): ${find}`);
  html = html.slice(0, first) + replacement + html.slice(first + find.length);
}

const W = 1280, H = 720, SEED = 20261009;

replaceOnce('<head>',
  '<head><!-- GENERATED by reference/port_check/make_capture_page.js from inkwood-renderer.html: ' +
  `DPR forced to 1, stage fixed at ${W}x${H}, a capture hook added. Do not edit; edit the prototype and re-run the script. -->`,
  'generated-file banner');

replaceOnce('const DPR=Math.min(2, window.devicePixelRatio||1);',
  'const DPR=1; /* capture page: was Math.min(2, window.devicePixelRatio||1) */',
  'force DPR 1');

replaceOnce('<div class="app">',
  '<style>/* capture page: the stage is exactly the Godot frame, whatever the window */\n' +
  'html,body{height:auto!important;overflow:auto!important}\n' +
  '.app{display:block!important;height:auto!important;min-height:0!important}\n' +
  `.stage{width:${W}px!important;height:${H}px!important;min-height:0!important;flex:none!important}\n` +
  '.panel{border-left:0!important}\n' +
  '#capture{position:fixed;top:10px;right:10px;z-index:10;display:none;gap:8px;align-items:center;' +
  'background:var(--panel);border:1px solid var(--line);border-radius:6px;padding:6px 8px;font:12px var(--f-mono)}\n' +
  '</style>\n<div class="app">',
  'fix the stage size');

replaceOnce('document.getElementById("count").textContent=',
  'window.__inkFrames=(window.__inkFrames||0)+1;document.getElementById("count").textContent=',
  'count rendered frames');

replaceOnce('</body>',
  `<div id="capture"><span id="captureInfo"></span><button type="button" class="btn primary" id="savePng">Save PNG</button></div>
<script>
// capture page additions (make_capture_page.js)
(() => {
  "use strict";
  const map = document.getElementById("map");
  let resolveReady;
  window.captureReady = new Promise(r => { resolveReady = r; });
  const wait = () => {
    if (!(window.__inkFrames >= 1)) { setTimeout(wait, 50); return; }
    window.captureMap = () => map.toDataURL("image/png");
    document.getElementById("captureInfo").textContent =
      "seed ${SEED} · " + map.width + "x" + map.height + (map.width === ${W} && map.height === ${H} ? "" : " (NOT ${W}x${H})");
    document.getElementById("capture").style.display = "flex";
    resolveReady({ width: map.width, height: map.height });
  };
  wait();  // polled with setTimeout, not rAF: rAF stops in a hidden tab
  document.getElementById("savePng").addEventListener("click", () => {
    const a = document.createElement("a");
    a.download = "inkwood_seed_${SEED}_" + map.width + "x" + map.height + ".png";
    a.href = window.captureMap();
    document.body.appendChild(a); a.click(); a.remove();
  });
})();
</script>
</body>`,
  'append the capture script');

fs.writeFileSync(outPath, html);
console.log(`wrote ${path.relative(process.cwd(), outPath)} (${html.length} bytes) from ${path.relative(process.cwd(), srcPath)}`);
