#!/usr/bin/env node
'use strict';
// Runs the PROTOTYPE'S OWN utility code and writes a fixed sample for seed
// 20261009 to expected_seed_20261009.json beside this file.
//
// The functions are sliced out of reference/inkwood-renderer.html by name and
// evaluated as they stand -- nothing is retyped -- so what this prints is what
// the browser computes. scripts/tests/test_port_utils.gd recomputes the same
// sample with the GDScript port and compares: RNG and noise bit for bit (the
// `bits` field is the little-endian IEEE-754 bytes of each double, the same
// bytes PackedFloat64Array.to_byte_array() gives), geometry to 1e-3 px.
//
// Re-run only when the prototype changes:   node reference/port_check/prototype_sample.js

const fs = require('fs');
const path = require('path');

const here = __dirname;
const html = fs.readFileSync(path.join(here, '..', 'inkwood-renderer.html'), 'utf8');

// Slice `function NAME(...) {...}` out of the page by brace matching.
function slice(name) {
  const start = html.indexOf(`function ${name}(`);
  if (start < 0) throw new Error(`prototype has no function ${name}`);
  let i = html.indexOf('{', start);
  let depth = 0;
  for (; i < html.length; i++) {
    if (html[i] === '{') depth++;
    else if (html[i] === '}' && --depth === 0) break;
  }
  return html.slice(start, i + 1);
}

const names = ['mulberry32', 'hash2', 'vnoise', 'fbm', 'hull', 'resample', 'chaikin'];
const U = new Function(names.map(slice).join('\n') + `\nreturn {${names.join(',')}};`)();
// buildRoad reads W, H and writes roadPts; its control points and 3 px spacing
// are inside it. Run it as-is at 1280x720 (the Godot viewport; the prototype
// itself takes W, H from the window).
const buildRoad = new Function('W', 'H', 'roadPts', slice('buildRoad') + '\nbuildRoad(); return roadPts;');

const dv = new DataView(new ArrayBuffer(8));
const bits = x => {
  dv.setFloat64(0, x, true);
  let s = '';
  for (let i = 0; i < 8; i++) s += dv.getUint8(i).toString(16).padStart(2, '0');
  return s;
};
const num = (x, extra = {}) => ({ ...extra, value: x, bits: bits(x) });
const pt = p => [p[0], p[1]];
// A point's bytes, x then y (32 hex digits): for the float64 geometry checks.
const pbits = p => bits(p[0]) + bits(p[1]);

const SEED = 20261009;
const out = { _about: 'Prototype output for seed 20261009, generated by prototype_sample.js from inkwood-renderer.html. Read by scripts/tests/test_port_utils.gd. Do not edit by hand.', seed: SEED };

// mulberry32: the first 16 draws.
{
  const rng = U.mulberry32(SEED);
  out.rng = Array.from({ length: 16 }, () => num(rng()));
}

// The prototype's sub-seed mint, `(rng()*2147483647)|0`: how every tree, prop,
// wall and house gets its own generator. Ints, compared as ints.
{
  const rng = U.mulberry32(SEED + 1);
  out.next_seed = { seed: SEED + 1, values: Array.from({ length: 8 }, () => (rng() * 2147483647) | 0) };
}

// INPUTS TRAVEL AS BYTES TOO. Godot's float parser (literals, to_float and
// JSON.parse_string alike) is not correctly rounded past 15 significant digits,
// so a 17-digit x or y could land one ulp off before the port even runs and fail
// the bit check for a reason that is not the port's. The GDScript side decodes
// xbits/ybits; x and y stay for reading.
const xy = (x, y) => ({ x, y, xbits: bits(x), ybits: bits(y) });

// hash2 at a few lattice cells, negatives and the int32 edges included.
out.hash2 = [
  [0, 0, 11], [1, 0, 11], [0, 1, 11], [1, 1, 11], [-1, -1, 11], [5, -7, 23],
  [123456, -654321, SEED], [2147483647, -2147483648, 7], [-2147483648, 2147483647, 1442695041],
  [40, 12, SEED % 9973 + 3], [3, 4, 1000 + 2 * 13],
].map(([i, j, s]) => num(U.hash2(i, j, s), { i, j, s }));

// vnoise at fractional positions, including the paper-tint scale the prototype uses.
out.vnoise = [
  [0.5, 0.5, 11], [3.25, -1.75, 23], [123.456, 789.012, 91], [-0.001, 0.999, SEED],
  [640 * 0.008, 360 * 0.008, 11], [1000.37, 2000.91, 1003], [7.3, 7.3, 424242],
].map(([x, y, s]) => num(U.vnoise(x, y, s), { ...xy(x, y), s }));

// fbm as the ground, dirt and tree-density passes call it.
out.fbm = [
  [0.37, 0.91, 11, 4], [100.5, 200.25, 23, 3], [-17.3, 42.8, SEED % 9973 + 3, 3],
  [300 * 0.008, 200 * 0.008, 11, 4], [300 * 0.0025, 200 * 0.0025, 23, 3], [512 * 0.011, 384 * 0.011, 91, 3],
  [1024 * 0.006, 768 * 0.006, SEED % 9973 + 3, 3],
].map(([x, y, s, o]) => num(U.fbm(x, y, s, o), { ...xy(x, y), s, o }));

// The shape of newScene's tree loop, from a fresh stream: x = rng()*W,
// y = rng()*H, f = fbm(x*.006, y*.006, seed%9973+3, 3), at 1280x720.
// Not a replay of the scene (newScene draws the fort, house and props
// first, and takes an extra rng() per candidate when f >= .5): it checks that
// the stream and the noise agree when consumed together.
{
  const W = 1280, H = 720, s = SEED % 9973 + 3;
  const rng = U.mulberry32(SEED);
  const draws = [];
  for (let i = 0; i < 12; i++) {
    const x = rng() * W, y = rng() * H;
    draws.push({ x: num(x), y: num(y), f: num(U.fbm(x * 0.006, y * 0.006, s, 3)) });
  }
  out.scene_sample = { w: W, h: H, s, draws };
}

// hull of 24 seeded points (prism shadows use this on footprints).
{
  const rng = U.mulberry32(77);
  const points = Array.from({ length: 24 }, () => [rng() * 100, rng() * 100]);
  out.hull = { points: points.map(pt), hull: U.hull(points).map(pt) };
}

// The road: buildRoad's control points at 1280x720, every 10th sample plus the last.
// xbits/ybits and control_bits carry the exact doubles for the float64 check
// (Geometry.catmull_rom_f64, which the scene generator places against).
{
  const W = 1280, H = 720;
  const control = [[-.1, .86], [.2, .77], [.47, .84], [.75, .71], [1.1, .64]].map(p => [p[0] * W, p[1] * H]);
  const road = buildRoad(W, H, []);
  const sample = i => ({ i, x: road[i].x, y: road[i].y, xbits: bits(road[i].x), ybits: bits(road[i].y) });
  const samples = [];
  for (let i = 0; i < road.length; i += 10) samples.push(sample(i));
  const last = road.length - 1;
  if (samples[samples.length - 1].i !== last) samples.push(sample(last));
  out.catmull_rom = { control: control.map(pt), control_bits: control.map(pbits), spacing: 3, count: road.length, samples };
}

// A freehand wall, smoothed and resampled as finishWall does it, open and closed.
{
  const rng = U.mulberry32(5);
  const src = Array.from({ length: 12 }, () => [rng() * 300, rng() * 200]);
  const run = closed => {
    const pts = U.resample(U.chaikin(U.chaikin(U.resample(src, 6, closed), closed), closed), 3, closed);
    const sample = i => ({ i, x: pts[i][0], y: pts[i][1], xbits: bits(pts[i][0]), ybits: bits(pts[i][1]) });
    const samples = [];
    for (let i = 0; i < pts.length; i += 5) samples.push(sample(i));
    const last = pts.length - 1;
    if (samples[samples.length - 1].i !== last) samples.push(sample(last));
    return { count: pts.length, samples, first: pt(pts[0]), last: pt(pts[last]) };
  };
  out.wall = { src: src.map(pt), src_bits: src.map(pbits), open: run(false), closed: run(true) };
}

const target = path.join(here, 'expected_seed_20261009.json');
fs.writeFileSync(target, JSON.stringify(out, null, 2) + '\n');

// The same lines test_port_utils.gd prints, for a side-by-side read.
const g = x => x.toPrecision(17).replace(/\.?0+$/, '');
console.log(`rng(${SEED}) first ${out.rng.length}: ${out.rng.map(e => g(e.value)).join(', ')}`);
console.log(`hash2: ${out.hash2.map(e => g(e.value)).join(', ')}`);
console.log(`vnoise: ${out.vnoise.map(e => g(e.value)).join(', ')}`);
console.log(`fbm: ${out.fbm.map(e => g(e.value)).join(', ')}`);
console.log(`scene draws: ${out.scene_sample.draws.map(d => `(${d.x.value.toFixed(3)}, ${d.y.value.toFixed(3)}) f=${d.f.value.toFixed(6)}`).join(', ')}`);
console.log(`hull: ${out.hull.hull.length} of ${out.hull.points.length} points, first (${out.hull.hull[0].join(', ')})`);
console.log(`road: ${out.catmull_rom.count} samples, first (${out.catmull_rom.samples[0].x}, ${out.catmull_rom.samples[0].y}), last (${out.catmull_rom.samples.at(-1).x}, ${out.catmull_rom.samples.at(-1).y})`);
for (const mode of ['open', 'closed']) {
  const w = out.wall[mode];
  console.log(`${mode} wall: ${w.count} points, first (${w.first.join(', ')}), last (${w.last.join(', ')})`);
}
console.log(`wrote ${path.relative(process.cwd(), target)}`);
