extends "res://scripts/test_support/test_case.gd"

# THE SCENE CHECK: the default scene -- seed 20261009 on a 1280x720 stage --
# generated by the GDScript port (scripts/world/scene_gen.gd) against what the
# PROTOTYPE'S OWN CODE generates under node
# (reference/port_check/prototype_scene.js -> expected_scene_20261009.json).
#
# WHAT IS COMPARED: object counts exactly; every tree's x, y, sr, hr, r, h,
# every prop's x, y, s, rot, h, every struct's scalars and every geometry point
# (wall centre line, normals, both edges, caps; house parts and corners), and
# every 10th road sample with its normal, within TOLERANCE; seeds, kinds, types
# and flags exactly. Expected doubles are decoded from the fixture's `bits`
# (hex_decode().decode_double(0)), never from its decimals -- Godot's float
# parser is not exact past 15 significant digits (CLAUDE.md, engine traps).
#
# NOT BIT-EXACT, BY DECISION. Alex, 2026-10-09: bit-exactness with the browser
# is not required; visual parity is the bar. The port happens to match node bit
# for bit today (0 mismatches at zero tolerance), but the check is a tolerance
# so that engine math or Vector2 on the placement path does not fail the gate
# on last-bit noise. A COUNT difference is still a real failure: the same seed
# drew a different scene.
#
# The parameters are checked too: data/params/render_defaults.json, read by
# RenderParams, must hold the prototype's own `P` defaults bit for bit. So is
# one freehand open wall with end caps, built outside the scene, because the
# default scene's walls never take wall_geom's caps branch.
#
# The summary is PRINTED in the format prototype_scene.js prints, so the .log
# reads side by side with node's output.

const RenderParams = preload("res://scripts/world/render_params.gd")
const SceneGen = preload("res://scripts/world/scene_gen.gd")
const Structures = preload("res://scripts/world/structures.gd")
const Geometry = preload("res://scripts/core/geometry.gd")
const Mulberry32 = preload("res://scripts/core/mulberry32.gd")

const FIXTURE := "res://reference/port_check/expected_scene_20261009.json"
# Bit mismatches beyond this many are counted, not listed: one wrong formula
# would otherwise list every object after it.
const MAX_LISTED := 25
# Relative, with the same absolute floor near zero. 1e-9 is a million times the
# last-bit noise this exists to forgive and a million times smaller than any
# difference that moves a pixel.
const TOLERANCE := 1e-9

var _compared := 0
var _mismatched := 0

static func bits(x: float) -> String:
	return PackedFloat64Array([x]).to_byte_array().hex_encode()

static func _close(a: float, b: float) -> bool:
	return absf(a - b) <= TOLERANCE * maxf(1.0, maxf(absf(a), absf(b)))

static func _f64(hex: Variant, offset: int = 0) -> float:
	return str(hex).hex_decode().decode_double(offset)

func _mismatch(message: String) -> void:
	_mismatched += 1
	if _mismatched <= MAX_LISTED:
		fail(message)

# One double against a fixture {value, bits}.
func exact(actual: Variant, entry: Variant, label: String) -> bool:
	_compared += 1
	if not (entry is Dictionary and (entry as Dictionary).has("bits")):
		_mismatch("%s -- fixture entry has no bits: %s" % [label, entry])
		return false
	if not (actual is float):
		_mismatch("%s -- port value is %s, not a float" % [label, type_string(typeof(actual))])
		return false
	var want := str(entry["bits"])
	if not _close(actual, _f64(want)):
		_mismatch("%s -- prototype %s (%s), port %s (%s)" % [label, String.num(_f64(want), 17), want, String.num(actual, 17), bits(actual)])
		return false
	return true

# A point list ([x, y] Arrays) against a fixture {values, bits}.
func exact_points(actual: Variant, entry: Variant, label: String) -> bool:
	if not (actual is Array):
		_mismatch("%s -- port has no point list" % label)
		return false
	var want: Array = (entry as Dictionary).get("bits", [])
	if not eq((actual as Array).size(), want.size(), "%s point count" % label):
		return false
	var ok := true
	for i in want.size():
		var p: Array = actual[i]
		var hex := str(want[i])
		for k in 2:
			_compared += 1
			var got: float = p[k]
			var expect_bits := hex.substr(k * 16, 16)
			if not _close(got, _f64(expect_bits)):
				ok = false
				_mismatch("%s[%d].%s -- prototype %s (%s), port %s (%s)" % [label, i, "xy"[k],
					String.num(_f64(expect_bits), 17), expect_bits, String.num(got, 17), bits(got)])
	return ok

func setup(_main) -> void:
	timeout_seconds = 120.0
	if not check(FileAccess.file_exists(FIXTURE), "fixture exists: %s (run `node reference/port_check/prototype_scene.js`)" % FIXTURE):
		finish()
		return
	var fx: Variant = JSON.parse_string(FileAccess.get_file_as_string(FIXTURE))
	if not check(fx is Dictionary, "fixture parses"):
		finish()
		return
	var seed_value: int = int(fx["seed"])
	eq(seed_value, 20261009, "the fixture is for the project's fixed scene seed")

	# --- parameters: the data file holds the prototype's P ----------------------
	var P := RenderParams.new()
	if not check(P.ok(), "render params load: %s" % ", ".join(P.errors)):
		finish()
		return
	var fp: Dictionary = fx["P"]
	for k: String in ["brush", "density", "treeSize", "sizeVar", "height", "sunAz", "elev", "shadowStr",
			"lw", "wob", "grain", "wallW", "wallH", "houseSize"]:
		exact(P.get(k), fp[k], "P.%s" % k)
	exact(float(P.rings), fp["rings"], "P.rings")
	eq(P.collide, fp["collide"], "P.collide")
	eq(P.shadowCol, Color.html(str(fp["shadowCol"])), "P.shadowCol")
	eq(P.L, fp["L"], "P.L (layer toggles)")
	var fc: Dictionary = fx["constants"]
	eq(P.CELL, float(fc["CELL"]), "CELL")
	eq(P.ROAD_HALF, float(fc["ROAD_HALF"]), "ROAD_HALF")
	exact(P.LX, fc["LX"], "LX")
	exact(P.LY, fc["LY"], "LY")

	# --- generate ------------------------------------------------------------------
	var t0 := Time.get_ticks_usec()
	var gen := SceneGen.new(float(fx["w"]), float(fx["h"]), P)
	gen.generate(seed_value)
	var ms := (Time.get_ticks_usec() - t0) / 1000.0
	exact(gen.max_cr(), fc["maxCr"], "maxCr()")

	# --- counts --------------------------------------------------------------------------
	var counts: Dictionary = fx["counts"]
	var walls: Array = gen.structs.filter(func(s: Dictionary) -> bool: return s.kind == "wall")
	var grid_objects := 0
	for k: Vector2i in gen.grid:
		grid_objects += (gen.grid[k] as Array).size()
	var trees_ok := eq(gen.trees.size(), int(counts["trees"]), "tree count")
	var props_ok := eq(gen.props.size(), int(counts["props"]), "prop count")
	var structs_ok := eq(gen.structs.size(), int(counts["structs"]), "structure count")
	eq(walls.size(), int(counts["walls"]), "wall count")
	eq(gen.structs.size() - walls.size(), int(counts["houses"]), "house count")
	var road_ok := eq(gen.roadPts.size(), int(counts["road"]), "road sample count")
	eq(gen.grid.size(), int(counts["grid_cells"]), "grid cell count")
	eq(grid_objects, int(counts["grid_objects"]), "grid object count")

	# --- road --------------------------------------------------------------------------------
	if road_ok:
		for e: Dictionary in fx["road"]:
			var i: int = int(e["i"])
			var p: Dictionary = gen.roadPts[i]
			for k: String in ["x", "y", "nx", "ny"]:
				exact(p[k], e[k], "road[%d].%s" % [i, k])

	# --- structures ----------------------------------------------------------------------------
	if structs_ok:
		for si in gen.structs.size():
			_check_struct(gen.structs[si], fx["structs"][si], "struct[%d]" % si)

	# --- props -----------------------------------------------------------------------------------
	if props_ok:
		for i in gen.props.size():
			var p: Dictionary = gen.props[i]
			var e: Dictionary = fx["props"][i]
			var label := "prop[%d]" % i
			eq(p.type, e["type"], label + ".type")
			eq(p.seed, int(e["seed"]), label + ".seed")
			for k: String in ["x", "y", "s", "rot", "h"]:
				exact(p[k], e[k], "%s.%s" % [label, k])

	# --- trees -----------------------------------------------------------------------------------
	if trees_ok:
		for i in gen.trees.size():
			var t: Dictionary = gen.trees[i]
			var e: Dictionary = fx["trees"][i]
			var label := "tree[%d]" % i
			eq(t.seed, int(e["seed"]), label + ".seed")
			eq(t.big, e["big"], label + ".big")
			for k: String in ["x", "y", "sr", "hr", "r", "h"]:
				exact(t[k], e[k], "%s.%s" % [label, k])

	# --- a freehand open wall with caps (not part of the scene) -------------------------------------
	# The default scene's walls are all closed or capless, so this is what checks
	# the "free" centre line and wall_geom's caps branch (atan2, the cap polygons,
	# the single outline loop) that castShadows and drawWall read. Same stroke as
	# prototype_scene.js: a seeded random walk through finishWall's pipeline.
	var free_line := "free wall: not built (stroke mismatch)"
	var fw: Dictionary = fx["free_wall"]
	var walk := Mulberry32.new(seed_value + 7)
	var stroke: Array = []
	var wx := 300.0
	var wy := 500.0
	for i in 30:
		wx += 8.0 + walk.next() * 4.0
		wy += (walk.next() - 0.5) * 10.0
		stroke.append([wx, wy])
	if exact_points(stroke, fw["stroke"], "free_wall.stroke"):
		var flat := Geometry.pairs_from_points(stroke)
		var fpts := Geometry.points_from_pairs(Geometry.resample_f64(Geometry.chaikin_f64(Geometry.chaikin_f64(
			Geometry.resample_f64(flat, 6.0, false), false), false), 3.0, false))
		var free := Structures.make_wall(Mulberry32.new(seed_value + 8), {"type": "free", "pts": fpts},
			{"closed": false, "caps": true})
		Structures.sync_struct(free, P)
		_check_struct(free, fw["wall"], "free_wall")
		free_line = ("free wall: %d pts, caps %d + %d pts, outline %d, seed %d" % [(free.pts as Array).size(),
			(free.caps[0] as Array).size(), (free.caps[1] as Array).size(), (free.outline[0] as Array).size(), free.seed])

	if _mismatched > MAX_LISTED:
		fail("... and %d more mismatches (%d listed above)" % [_mismatched - MAX_LISTED, MAX_LISTED])

	# --- the summary, in prototype_scene.js's format ------------------------------------------------
	print("scene %d at %dx%d: %d trees, %d props, %d structures (%d walls, %d houses), road %d samples, grid %d cells / %d objects" % [
		seed_value, int(gen.W), int(gen.H), gen.trees.size(), gen.props.size(), gen.structs.size(),
		walls.size(), gen.structs.size() - walls.size(), gen.roadPts.size(), gen.grid.size(), grid_objects])
	var wall_parts: Array[String] = []
	for s: Dictionary in walls:
		wall_parts.append("%s %d pts seed %d" % [s.gen.type, (s.pts as Array).size(), s.seed])
	print("walls: ", ", ".join(wall_parts))
	if gen.trees.size() > 0:
		var t: Dictionary = gen.trees[0]
		print("first tree: (%s, %s) r=%s h=%s seed=%d big=%s" % [_g(t.x), _g(t.y), _g(t.r), _g(t.h), t.seed, t.big])
	if gen.props.size() > 0:
		var p: Dictionary = gen.props[0]
		print("first prop: %s (%s, %s) s=%s seed=%d" % [p.type, _g(p.x), _g(p.y), _g(p.s), p.seed])
	print(free_line)
	print("generated in %.0f ms; %d doubles compared within %s, %d mismatched" % [ms, _compared, str(TOLERANCE), _mismatched])
	finish()

func _check_struct(s: Dictionary, e: Dictionary, label: String) -> void:
	if not eq(s.kind, e["kind"], label + ".kind"):
		return
	eq(s.seed, int(e["seed"]), label + ".seed")
	for k: String in ["hs", "h"]:
		exact(s[k], e[k], "%s.%s" % [label, k])
	for k: String in ["bx", "by", "bw", "bh"]:
		eq(s.get(k), float(e[k]), "%s.%s" % [label, k])
	if s.kind == "wall":
		eq(s.closed, e["closed"], label + ".closed")
		exact(s.ws, e["ws"], label + ".ws")
		exact(s.hw, e["hw"], label + ".hw")
		var g: Dictionary = s.gen
		var eg: Dictionary = e["gen"]
		eq(g.keys().size(), eg.keys().size(), label + ".gen field count")
		for k: String in eg:
			if eg[k] is Dictionary and (eg[k] as Dictionary).has("value"):
				exact(g.get(k), eg[k], "%s.gen.%s" % [label, k])
			elif eg[k] is Dictionary:  # a point list, {values, bits}
				exact_points(g.get(k), eg[k], "%s.gen.%s" % [label, k])
			else:
				eq(g.get(k), eg[k], "%s.gen.%s" % [label, k])
		for k: String in ["pts", "nrm", "L", "R"]:
			exact_points(s[k], e[k], "%s.%s" % [label, k])
		var caps: Array = s.caps
		if eq(caps.size(), (e["caps"] as Array).size(), label + ".caps count"):
			for ci in caps.size():
				exact_points(caps[ci], e["caps"][ci], "%s.caps[%d]" % [label, ci])
		var outline_sizes: Array = []
		for o: Array in s.outline:
			outline_sizes.append(float(o.size()))
		eq(outline_sizes, e["outline"], label + ".outline ring sizes")
		var edges: Array = []
		for ed: Dictionary in s.edges:
			edges.append({"n": float((ed.p as Array).size()), "closed": ed.closed})
		eq(edges, e["edges"], label + ".edges")
	else:
		for k: String in ["x", "y", "rot"]:
			exact(s[k], e[k], "%s.%s" % [label, k])
		eq(s.chimney, e["chimney"], label + ".chimney")
		if eq((s.parts as Array).size(), (e["parts"] as Array).size(), label + ".parts count"):
			for pi in (s.parts as Array).size():
				for k: String in ["ox", "oy", "w", "d", "r"]:
					exact(s.parts[pi][k], e["parts"][pi][k], "%s.parts[%d].%s" % [label, pi, k])
		if eq((s.geo as Array).size(), (e["geo"] as Array).size(), label + ".geo count"):
			for gi in (s.geo as Array).size():
				var gp: Dictionary = s.geo[gi]
				var ep: Dictionary = e["geo"][gi]
				for k: String in ["cx", "cy", "w", "d", "cc", "ss"]:
					exact(gp[k], ep[k], "%s.geo[%d].%s" % [label, gi, k])
				exact_points(gp.corners, ep["corners"], "%s.geo[%d].corners" % [label, gi])
				# tf (the Callable) is the corners' own transform: it must give them back.
				var w: float = gp.w
				var d: float = gp.d
				eq(gp.tf.call(-w / 2.0, -d / 2.0), gp.corners[0], "%s.geo[%d].tf matches corners[0]" % [label, gi])

# 17 significant digits, trailing zeros dropped -- prototype_scene.js prints
# toPrecision(17) the same way (see test_port_utils._fmt for why not %g).
static func _g(v: float) -> String:
	var e := 0
	if v != 0.0:
		e = floori(log(absf(v)) / log(10.0))
		if absf(v) >= pow(10.0, e + 1):
			e += 1
		elif absf(v) < pow(10.0, e):
			e -= 1
	return String.num(v, maxi(0, 16 - e))
